version: "3.3"
services:
    app:
      build:
        args:
          user: user
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      image: techhunt2020
      container_name: techhunt2020-app
      restart: unless-stopped
      working_dir: /var/www/
      volumes:
        - ./:/var/www
      networks:
        - techhunt2020net
  
    db:
      image: mysql:5.7
      container_name: techhunt2020-db
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
      volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      networks:
        - techhunt2020net
  
    nginx:
      image: nginx:alpine
      container_name: techhunt2020-nginx
      restart: unless-stopped
      ports:
        - 8000:80
      volumes:
        - ./:/var/www
        - ./docker-compose/nginx:/etc/nginx/conf.d/
      networks:
        - techhunt2020net

networks:
  techhunt2020net:
    driver: bridge